tims shi

In [3]:
import pandas as pd
FILE_PATH = "../data/00-raw/MxMH_Survey/mxmh_survey_results.csv"
df = pd.read_csv(FILE_PATH)

In [4]:
df.head()

,Timestamp,Age,Primary streaming service,Hours per day,While working,Instrumentalist,Composer,Fav genre,Exploratory,Foreign languages,...,Frequency [R&B],Frequency [Rap],Frequency [Rock],Frequency [Video game music],Anxiety,Depression,Insomnia,OCD,Music effects,Permissions
0,8/27/2022 19:29:02,18.0,Spotify,3.0,Yes,Yes,Yes,Latin,Yes,Yes,...,Sometimes,Very frequently,Never,Sometimes,3.0,0.0,1.0,0.0,NaN,I understand.
1,8/27/2022 19:57:31,63.0,Pandora,1.5,Yes,No,No,Rock,Yes,No,...,Sometimes,Rarely,Very frequently,Rarely,7.0,2.0,2.0,1.0,NaN,I understand.
2,8/27/2022 21:28:18,18.0,Spotify,4.0,No,No,No,Video game music,No,Yes,...,Never,Rarely,Rarely,Very frequently,7.0,7.0,10.0,2.0,No effect,I understand.
3,8/27/2022 21:40:40,61.0,YouTube Music,2.5,Yes,No,Yes,Jazz,Yes,Yes,...,Sometimes,Never,Never,Never,9.0,7.0,3.0,3.0,Improve,I understand.
4,8/27/2022 21:54:47,18.0,Spotify,4.0,Yes,No,No,R&B,Yes,No,...,Very frequently,Very frequently,Never,Rarely,7.0,2.0,5.0,9.0,Improve,I understand.

In [5]:
df.describe()

,Age,Hours per day,BPM,Anxiety,Depression,Insomnia,OCD
count,735.000000,736.000000,6.290000e+02,736.000000,736.000000,736.000000,736.000000
mean,25.206803,3.572758,1.589948e+06,5.837636,4.796196,3.738451,2.637228
std,12.054970,3.028199,3.987261e+07,2.793054,3.028870,3.088689,2.842017
min,10.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,18.000000,2.000000,1.000000e+02,4.000000,2.000000,1.000000,0.000000
50%,21.000000,3.000000,1.200000e+02,6.000000,5.000000,3.000000,2.000000
75%,28.000000,5.000000,1.440000e+02,8.000000,7.000000,6.000000,5.000000
max,89.000000,24.000000,1.000000e+09,10.000000,10.000000,10.000000,10.000000

In [7]:
df.isna().value_counts()

Timestamp  Age    Primary streaming service  Hours per day  While working  Instrumentalist  Composer  Fav genre  Exploratory  Foreign languages  BPM    Frequency [Classical]  Frequency [Country]  Frequency [EDM]  Frequency [Folk]  Frequency [Gospel]  Frequency [Hip hop]  Frequency [Jazz]  Frequency [K pop]  Frequency [Latin]  Frequency [Lofi]  Frequency [Metal]  Frequency [Pop]  Frequency [R&B]  Frequency [Rap]  Frequency [Rock]  Frequency [Video game music]  Anxiety  Depression  Insomnia  OCD    Music effects  Permissions
False      False  False                      False          False          False            False     False      False        False              False  False                  False                False            False             False               False                False             False              False              False             False              False            False            False            False             False                         False    False       False     False  False          False          616
                                                                                                                                                 True   False                  False                False            False             False               False                False             False              False              False             False              False            False            False            False             False                         False    False       False     False  False          False          102
                                                                                                                                                 False  False                  False                False            False             False               False                False             False              False              False             False              False            False            False            False             False                         False    False       False     False  True           False            5
                                                                                                                              True               False  False                  False                False            False             False               False                False             False              False              False             False              False            False            False            False             False                         False    False       False     False  False          False            3
                                                                           True             False     False      False        False              False  False                  False                False            False             False               False                False             False              False              False             False              False            False            False            False             False                         False    False       False     False  False          False            3
                                                                           False            False     False      False        False              True   False                  False                False            False             False               False                False             False              False              False             False              False            False            False            False             False                         False    False       False     False  True           False            2
                                                            True           False            False     False      False        False              False  False                  False                False            False             False               False                False             False              False              False             False              False            False            False            False             False                         False    False       False     False  False          False            1
                                                                                                                                                 True   False                  False                False            False             False               False                False             False              False              False             False              False            False            False            False             False                         False    False       False     False  False          False            1
                                                                           True             True      False      False        True               True   False                  False                False            False             False               False                False             False              False              False             False              False            False            False            False             False                         False    False       False     False  True           False            1
                  True                       False          False          False            False     False      False        False              False  False                  False                False            False             False               False                False             False              False              False             False              False            False            False            False             False                         False    False       False     False  False          False            1
           True   False                      False          False          False            False     False      False        False              True   False                  False                False            False             False               False                False             False              False              False             False              False            False            False            False             False                         False    False       False     False  False          False            1
Name: count, dtype: int64